name = "skillstak"
compatibility_date = "2024-11-11"
pages_build_output_dir = "build/client"

[vars]
# set ADSENSE_CLIENT="ca-pub-xxxxxxxx" to enable ad footer
ADSENSE_CLIENT = ""
APP_BASE_URL = "https://www.skillstak.com"
# Optional Email SMTP creds if you want direct SMTP from Worker (or use an external free tier)
SMTP_HOST = ""
SMTP_PORT = ""
SMTP_USER = ""
SMTP_PASS = ""
SMTP_FROM = "no-reply@yourdomain.com"
# Google OAuth placeholders
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_REDIRECT_URI = ""

[[d1_databases]]
binding = "SKILLSTAK_DB"
database_name = "skillstak-db"
database_id = "dcf58c15-f3f1-4904-8307-82b7a100ee1e"

[[kv_namespaces]]
binding = "SKILLSTAK_SESSIONS"
id = "d67e794cc58344848995d50b694a256d"
