name = "skillstak"
compatibility_date = "2024-11-11"

[vars]
# set ADSENSE_CLIENT="ca-pub-xxxxxxxx" to enable ad footer
ADSENSE_CLIENT = ""
APP_BASE_URL = "https://www.skillstak.com"
# Optional Email SMTP creds if you want direct SMTP from Worker (or use an external free tier)
SMTP_HOST = ""
SMTP_PORT = ""
SMTP_USER = ""
SMTP_PASS = ""
SMTP_FROM = "no-reply@yourdomain.com"
# Google OAuth placeholders
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_REDIRECT_URI = ""

[[d1_databases]]
binding = "SKILLSTAK_DB"
database_name = "skillstak-db"
database_id = "aed633f0-45dc-45c5-8308-cda6475df572"

[[kv_namespaces]]
binding = "SKILLSTAK_SESSIONS"
id = "REPLACE_WITH_KV_ID"

main = "build/server/index.js"
