// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/reset": {
    params: {};
  };
  "/reset/:token": {
    params: {
      "token": string;
    };
  };
  "/test-sentry": {
    params: {};
  };
  "/p/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/p/:projectId/edit": {
    params: {
      "projectId": string;
    };
  };
  "/p/:projectId/review": {
    params: {
      "projectId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/logout" | "/reset" | "/reset/:token" | "/test-sentry" | "/p/:projectId" | "/p/:projectId/edit" | "/p/:projectId/review" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/reset.request.tsx": {
    id: "routes/reset.request";
    page: "/reset";
  };
  "routes/reset.$token.tsx": {
    id: "routes/reset.$token";
    page: "/reset/:token";
  };
  "routes/test-sentry.tsx": {
    id: "routes/test-sentry";
    page: "/test-sentry";
  };
  "routes/p.$projectId.tsx": {
    id: "routes/p.$projectId";
    page: "/p/:projectId" | "/p/:projectId/edit" | "/p/:projectId/review";
  };
  "routes/p.$projectId._index.tsx": {
    id: "routes/p.$projectId._index";
    page: "/p/:projectId";
  };
  "routes/p.$projectId.edit.tsx": {
    id: "routes/p.$projectId.edit";
    page: "/p/:projectId/edit";
  };
  "routes/p.$projectId.review.tsx": {
    id: "routes/p.$projectId.review";
    page: "/p/:projectId/review";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/reset.request": typeof import("./app/routes/reset.request.tsx");
  "routes/reset.$token": typeof import("./app/routes/reset.$token.tsx");
  "routes/test-sentry": typeof import("./app/routes/test-sentry.tsx");
  "routes/p.$projectId": typeof import("./app/routes/p.$projectId.tsx");
  "routes/p.$projectId._index": typeof import("./app/routes/p.$projectId._index.tsx");
  "routes/p.$projectId.edit": typeof import("./app/routes/p.$projectId.edit.tsx");
  "routes/p.$projectId.review": typeof import("./app/routes/p.$projectId.review.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};